# This is a basic workflow that is manually triggered

name: Deploy Podcast workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildDocker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Generate Podcast
        run: |
          ${GITHUB_WORKSPACE}/runBlogCast.sh

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions.github@soft-wa.re"

      - name: commit
        run: |
          git add *.mp3
          git reset --soft origin/deployProd
          git commit --amend -m "buildbot@soft-wa.re"
          git push origin +HEAD:deployProd
